### ISSUE TITLE
About downloadmanga program

### ISSUE THREAD

**Issue by ghost** [mashingan/nim-etc#1]
Hey, nice script you got there. Since I read manga (mostly printed) I thought to try it too. I made some changes and thought you would like to try [them](https://gist.github.com/konqoro/b0d695d2f50e02f6842eea12a2377117) Cheers!

**Comment by mashingan** [comment]
Thanks. Since I never intended to use it as library, I purposely didn't include ``when isMainModule``.  

I just wrote it for fun 😆 

Oh, you removed the ``getInfo`` proc to be immediately used in ``process`` proc and edited several changes. That's nice. Thank you
